### ISSUE TITLE
@机器人后依然用前缀判断是否回答

### ISSUE THREAD

**Issue by Jerry-Z07** [yejue/nonebot-plugin-with-ai-agents#12]
机器上部署了多个bot实例  
假设这个插件在实例A上
如果我要使用实例B的命令，@ 机器人并输入文字后，就算有命令前缀，依然会触发ai回答  
希望能增加在@机器人后，依然需要判断前缀以回答的功能（独立前缀）

**Comment by yejue** [comment]
没看明白，你是说，at 哪个机器人，触发了哪个机器人回答

**Comment by Jerry-Z07** [comment]
抱歉，是我表述不清  
就是给这个插件的触发定义一个独立、不同于command_start的前缀（用户自行在.env文件中定义）

**Comment by yejue** [comment]
> 抱歉，是我表述不清 就是给这个插件的触发定义一个独立、不同于command_start的前缀（用户自行在.env文件中定义）

如果你要多开 bot，修改 .env 的 start 就可以了。插件内已经有了 command start 来判断，这已经具备了命令触发的唯一性，没有理由再去添加累赘的东西。如果你是同一份代码运行两个 bot，这本来就不是一个好的做法
