### ISSUE TITLE
启动报错 AttributeError：type object BaseModel has no attribute model_config

### ISSUE THREAD

**Issue by lin6953** [yejue/nonebot-plugin-with-ai-agents#3]
![image](https://github.com/yejue/nonebot-plugin-with-ai-agents/assets/107689301/278c3529-ec33-4a73-b860-3af83c868fe5)

**Comment by yejue** [comment]
已收到，现在在外玩，晚些时候测试
你的 with ai agents 版本号是多少

**Comment by lin6953** [comment]
直接拉的最新的

**Comment by yejue** [comment]
> 直接拉的最新的

直接拉的依赖版本可能不对，你 pip 安装一下看看

**Comment by lin6953** [comment]
> > 直接拉的最新的
> 
> 直接拉的依赖版本可能有效，你 pip 安装看看一下

pip部署拉的最新版本
![image](https://github.com/yejue/nonebot-plugin-with-ai-agents/assets/107689301/4be5497c-71a6-46c8-8198-1b46f33f7c29)

**Comment by yejue** [comment]
> > > 直接拉的最新的
> > 
> > 
> > 直接拉的依赖版本可能有效，你 pip 安装看看一下
> 
> pip部署拉的最新版本 ![image](https://private-user-images.githubusercontent.com/107689301/331861823-4be5497c-71a6-46c8-8198-1b46f33f7c29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNjkwNTUsIm5iZiI6MTcxNjE2ODc1NSwicGF0aCI6Ii8xMDc2ODkzMDEvMzMxODYxODIzLTRiZTU0OTdjLTcxYTYtNDZjOC04MTk4LTFiNDZmMzNmN2MyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwMTMyMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTA4NmU3YWI2NjVhMzFlNzFiMzk2OTJiNDA0OGRlNDBkOGU1YTQwMmZmMDhmOTI0N2M5YWUzNzE4ZWI5ZTFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JsGhO-f5-v6UrdbqrDYCIKf-Iwf3ADNhHPekg59jrMY)


在设置中，我使用了 model_config 属性来取消一些 Warning，你本地可能存在两个 pydantic 版本，其中一个 pydantic 没有这个属性，需要的是 2.0+ 版本的 pydantic。你可以看一下 pip list，确认信息，卸载两个 pydantic 再安装

**Comment by yejue** [comment]
现在模块更新到了 0.1.12，不强制使用这个设置，可以将模块删除重新安装。
```
pip uninstall nonebot-plugin-with-ai-agents
nb plugin install nonebot-plugin-with-ai-agents
```

**Comment by lin6953** [comment]
> 现在模块更新到了 0.1.12，不强制使用这个设置，可以将模块删除重新安装。
> ```
> pip uninstall nonebot-plugin-with-ai-agents
> nb plugin install nonebot-plugin-with-ai-agents
> ```

好的，大佬辛苦了
