### ISSUE TITLE
中转的openai

### ISSUE THREAD

**Issue by lin6953** [yejue/nonebot-plugin-with-ai-agents#4]
可以使用中转的openai吗？需要怎么更改设置

**Comment by yejue** [comment]
> 可以使用中转的openai吗？需要怎么更改设置

什么叫中转的 openai。目前这个模块没有提供更改 AI 接口来源的配置。

**Comment by yejue** [comment]
无明确需求，关闭，后续如有回复可继续在此 ISSUE 中更新
