### ISSUE TITLE
【功能建议】为插件设置一个消息匹配前缀，满足“XXX” 前缀的消息才会被响应

### ISSUE THREAD

**Issue by JustinHuangber** [yejue/nonebot-plugin-with-ai-agents#5]
是否可以添加此插件的指令前缀，在群聊环境中容易误触（群友喜欢引用机器人的话）

**Comment by yejue** [comment]
> 是否可以添加此插件的指令前缀，在群聊环境中容易误触（群友喜欢引用机器人的话）

可以，明天更新

**Comment by yejue** [comment]
0.1.13 更新后增加消息前缀配置、插件优先级配置
